# 应用名称
spring:
  application:
    name: '@project.name@'
    version: '@project.version@'
  main:
    allow-bean-definition-overriding: true
  # jpa数据库配置
  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_example?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: L0ngh)1026
    continue-on-error: true
    hikari:
      pool-name: '@build.finalName@Pool'
      # maximum number of milliseconds that a client will wait for a connection
      connection-timeout: 20000
      # minimum number of idle connections maintained by HikariCP in a connection pool
      minimum-idle: 10
      # maximum pool size
      maximum-pool-size: 3
      # maximum idle time for connection
      idle-timeout: 10000
      # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      max-lifetime: 1000
      # default auto-commit behavior.
      auto-commit: true
  # 序列化操作，不包含null的值
  jackson:
    default-property-inclusion: non_null
    date-format: 'yyyy-MM-dd'


# 服务器
## configure port and context path
server:
  port: 9999
  http2:
    enabled: true
  servlet:
    encoding:
      enabled: true
      charset: utf-8
      force: true
    context-path: '/@project.artifactId@/'
  # 返回结果压缩
  compression:
    enabled: true
  error:
    whitelabel:
      enabled: false
    include-exception: true
    include-stacktrace: on_trace_param
  # Tomcat settings
  tomcat:
    uri-encoding: UTF-8
    max-connections: 10000
    accept-count: 1000
    max-swallow-size: 200MB
    max-http-form-post-size: 200MB
    threads:
      min-spare: 30
      max: 200
  netty:
    connection-timeout: 30000



