# 应用名称
spring:
  application:
    name: '@project.name@'
    version: '@project.version@'
  main:
    allow-bean-definition-overriding: true
  jmx:
    enabled: true

server:
  port: 8081
  servlet:
    context-path: /
# grpc server配置
grpc:
  enabled: true
  port: 6565
  enable-reflection: true


