const keys = {
  // 默认语言设置
  LANG_NAME: 'lang',
  // 全局配置
  SIDEBAR_TYPE: 'SIDEBAR_TYPE',
  DEFAULT_THEME: 'DEFAULT_THEME',
  DEFAULT_LAYOUT_MODE: 'DEFAULT_LAYOUT_MODE',
  DEFAULT_COLOR: 'DEFAULT_COLOR',
  DEFAULT_COLOR_WEAK: 'DEFAULT_COLOR_WEAK',
  DEFAULT_FIXED_HEADER: 'DEFAULT_FIXED_HEADER',
  DEFAULT_FIXED_SIDEMENU: 'DEFAULT_FIXED_SIDEMENU',
  DEFAULT_FIXED_HEADER_HIDDEN: 'DEFAULT_FIXED_HEADER_HIDDEN',
  DEFAULT_CONTENT_WIDTH_TYPE: 'DEFAULT_CONTENT_WIDTH_TYPE',
  DEFAULT_MULTI_TAB: 'DEFAULT_MULTI_TAB',
  // 用户登录信息
  LOGIN_INFO: 'info',
  LOGIN_TOKEN: 'token'
}
export default keys
