const names = {
  // 系统配置信息参数
  SET_SIDEBAR_TYPE: 'SET_SIDEBAR_TYPE',
  CLOSE_SIDEBAR: 'CLOSE_SIDEBAR',
  TOGGLE_DEVICE: 'TOGGLE_DEVICE',
  TOGGLE_THEME: 'TOGGLE_THEME',
  TOGGLE_LAYOUT_MODE: 'TOGGLE_LAYOUT_MODE',
  TOGGLE_FIXED_HEADER: 'TOGGLE_FIXED_HEADER',
  TOGGLE_FIXED_SIDERBAR: 'TOGGLE_FIXED_SIDERBAR',
  TOGGLE_FIXED_HEADER_HIDDEN: 'TOGGLE_FIXED_HEADER_HIDDEN',
  TOGGLE_CONTENT_WIDTH: 'TOGGLE_CONTENT_WIDTH',
  TOGGLE_COLOR: 'TOGGLE_COLOR',
  TOGGLE_WEAK: 'TOGGLE_WEAK',
  TOGGLE_MULTI_TAB: 'TOGGLE_MULTI_TAB',
  // 动态路由相关
  UPDATE_ROUTES: 'UPDATE_ROUTES',
  // 用户登录相关常量store
  UPDATE_LOGIN_TOKEN: 'UPDATE_LOGIN_TOKEN',
  UPDATE_LOGIN_INFO: 'UPDATE_LOGIN_INFO',
  UPDATE_ROLES: 'UPDATE_ROLES',
  UPDATE_LOGOUT: 'UPDATE_LOGOUT'
}
export default names
