const names = {
  // 动态路由相关
  UPDATE_ROUTES: 'UPDATE_ROUTES',
  // 用户登录相关常量store
  UPDATE_LOGIN_TOKEN: 'UPDATE_LOGIN_TOKEN',
  UPDATE_LOGIN_INFO: 'UPDATE_LOGIN_INFO',
  UPDATE_LOGGED: 'UPDATE_LOGGED',
  UPDATE_ROLES: 'UPDATE_ROLES',
  UPDATE_LOGOUT: 'UPDATE_LOGOUT'
}
export default names
